tried a few things: --preserve-commit-hashes for git-filter-repo; --rebase in git-mrt push

diff --git a/git-mrt b/git-mrt
--- a/git-mrt
+++ b/git-mrt
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VERSION="1.0"
+VERSION="1.09"
 
 # Exit with return code
 # $1 - message to output in stderr
@@ -10,7 +10,7 @@ function die() {
     exit ${2:-1}
 }
 
-declare -A LOG_LEVELS
+#declare -A LOG_LEVELS
 LOG_LEVELS=([0]="ERROR" [1]="WARN" [2]="INFO" [3]="DEBUG")
 
 VERBOSITY=2
@@ -162,7 +162,7 @@ function cleanup_monorepo() {
     log "Cleaning up the local monorepo"
     cd $MONOPATH
     git checkout -q $MONOBRANCH
-    git branch | grep -v $MONOBRANCH | xargs git branch -D &> /dev/null
+    git branch | grep -v ^* | xargs git branch -D &> /dev/null
     git remote rm temp &> /dev/null
 }
 
@@ -171,8 +171,10 @@ function extract_subdirectory() {
     log "Extracting the subdirectory into the temporary monorepo branch 'filter-repo'"
     cd $MONOPATH
     git checkout -b filter-repo || die "[FATAL] Failed to create the branch 'filter-repo'"
-    #git filter-repo --prune-degenerate=always --force --subdirectory-filter "$1" --refs filter-repo
-    git filter-repo --force --subdirectory-filter "$1" --refs filter-repo
+    # Tried these threee options, but did not see any effects on results:
+    #    --replace-refs delete-no-add --preserve-commit-hashes --prune-degenerate=always
+    local extra_args="--replace-refs delete-no-add --preserve-commit-hashes"
+    git filter-repo $extra_args --force --subdirectory-filter "$1" --refs filter-repo
     if [ $? -ne 0 ]; then
         cleanup_monorepo
         die "[FATAL] Failed to perform filter-repo on $1"
@@ -208,7 +210,7 @@ function mrt__clone() {
     log "Initializing a subrepo"
     mkdir $subrepopath || die "[FATAL] Failed to create the subrepo dir"
     cd $subrepopath 
-    git init -q
+    git init -q -b main
 
     extract_subdirectory $subdirectory
     update_subrepo $subrepopath
@@ -261,12 +263,14 @@ function mrt__push() {
     fi
 
     # Another way: rewriting local subrepo to a branch 'filter-repo' as extract_subdirectory()
+    # 08/21/2022: tried the above, but did not make it work
     log "Rewriting local subrepo to a temporary repo with git filter-repo" 
     local tempdir="$(mktemp -d -t "${subdirectory##*/}.XXXX")"
     git clone $subrepopath $tempdir
     cd $tempdir
-    #git filter-repo --prune-degenerate=always --force --to-subdirectory-filter $subdirectory
-    git filter-repo --force --to-subdirectory-filter $subdirectory
+    #    --replace-refs delete-no-add --preserve-commit-hashes --prune-degenerate=always
+    local extra_args="--replace-refs delete-no-add --preserve-commit-hashes"
+    git filter-repo $extra_args --force --to-subdirectory-filter $subdirectory 
     [ $? -ne 0 ] && die "[FATAL] git filter-repo failed to re-write history"
 
     log "Switching the local monorepo to a branch to be pushed"
@@ -276,16 +280,30 @@ function mrt__push() {
 
     log "Merging the temporary repo to the local monorepo branch" 
     git remote add temp $tempdir
+    # --rebase does not work
+    #git pull temp $subrepobranch --rebase 
     git fetch temp
-    git merge --allow-unrelated-histories --no-edit temp/$subrepobranch
+    # --ff-only will always fail
+    git merge --ff-only temp/$subrepobranch
     if [ $? -ne 0 ]; then
-        log "Aborting merge"
-        git merge --abort
-        cleanup_monorepo 
-        die "[FATAL] Merge failed"
+        local merge_args="--allow-unrelated-histories --no-edit"
+        log "Failed to merge with --ff-only, try $merge_args"
+        # DO NOT push if 'Already up to date.'
+        git merge $merge_args temp/$subrepobranch | xargs | grep "Already up to date"
+        if [ $? -eq 0 ]; then
+            cleanup_monorepo 
+            die "[FATAL] No pushing because of already up to date"
+        fi
+
+        git merge $merge_args temp/$subrepobranch
+        if [ $? -ne 0 ]; then
+            log "Aborting merge"
+            git merge --abort
+            cleanup_monorepo 
+            die "[FATAL] Merge failed"
+        fi
     fi
 
-    # To-do: DO NOT push if 'Already up to date.'
     log "Pushing local monorepo changes to upstream"
     git push --set-upstream origin $monorepobranch
     if [ $? -ne 0 ]; then
